DROP TABLE IF EXISTS participation;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS places;
DROP TABLE IF EXISTS accounts;
DROP TYPE IF EXISTS Role;
DROP TYPE IF EXISTS EventType;
DROP FUNCTION IF EXISTS head(text);
