# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/orm/schema.rs"
generate_missing_sql_type_definitions = false
import_types = ["diesel::sql_types::*", "crate::orm::utils::sql_types::*"]

[migrations_directory]
dir = "migrations"
